include:
  - https://gitlab.com/jitesoft/gitlab-ci-lib/raw/master/code_quality.yml
  - https://gitlab.com/jitesoft/gitlab-ci-lib/raw/master/dependency_scanning.yml

stages:
  - test
  - scan

test:
  stage: test
  image: jitesoft/composer
  script:
    - composer install --prefer-dist --no-progress
    - composer test

scan:dep:
  extends: .dependency_scanning

scan:code:
  extends: .code_quality
