include:
  template: Dependency-Scanning.gitlab-ci.yml

stages:
  - test
  - scan

test:
  stage: test
  image: registry.gitlab.com/jitesoft/dockerfiles/phpunit:7.2
  script:
    - composer install --prefer-dist --no-progress
    - composer test

scan:
  stage: scan
  image: registry.gitlab.com/gitlab-org/security-products/analyzers/gemnasium:2
  script:
    - ./analyser run
  artifacts:
    reports:
      dependency_scanning: gl-dependency-scanning-report.json
