include:
  - https://gitlab.com/jitesoft/gitlab-ci-lib/raw/master/code_quality.yml
  - https://gitlab.com/jitesoft/gitlab-ci-lib/raw/master/dependency_scanning.yml

stages:
  - test
  - scan

test:
  stage: test
  image: registry.gitlab.com/jitesoft/dockerfiles/phpunit:7.2
  script:
    - composer install --prefer-dist --no-progress
    - composer test

scan:dep:
  extends: .dependency_scanning

scan:code:
  extends: .code_quality
