stages:
  - test

test:
  stage: test
  image: registry.gitlab.com/jitesoft/dockerfiles/phpunit:7.2
  script:
    - composer install --prefer-dist --no-progress
    - composer test

scan:
  stage: test
  image: registry.gitlab.com/gitlab-org/security-products/analyzers/gemnasium:2
  before_script:
    - mv /analyzer /usr/local/bin
  script:
    - analyzer run
  artifacts:
    reports:
      dependency_scanning: gl-dependency-scanning-report.json
